services:
  - type: web
    plan: free
    region: singapore
    name: life-beyond-the-waitlist
    runtime: python
    repo: https://github.com/FAM-50341/Life-Beyond-The-WaitList
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
