services:
  - type: web
    name: life-beyond-the-waitlist
    env: python
    repo: https://github.com/FAM-50341/Life-Beyond-The-WaitList
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    plan: free
